name: Deloy

# 提交到 develop 才会触发
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '8.11.1'
    - run: npm install
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: '8.11.1'
    - run: npm install
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x' 
    - name: Build
      run: npm run build
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: site
        path: _site
